---
sudo: required
dist: trusty
language: bash
services:
  - docker
before_install:
  - docker pull mmckinst/rpmbuilder
  - sudo apt-get -qq update
#  - sudo apt-get install -y rpm wget
  - mkdir -p BUILD RPMS SOURCES SPECS SRPMS
env:
  - MOCK_CONFIG="epel-6-i386"
  - MOCK_CONFIG="epel-6-x86_64"
  - MOCK_CONFIG="epel-7-x86_64"
script:

# these steps are done in rpmbuilder.sh with spectool and mock inside the docker
# containter. tbd how to handle this for cases where building an rpm for a
# private repo or one where you can't just download the src.rpm
#  - rpmspec -P  SPECS/mg.spec | awk '/^Source/ {print $2}' | xargs -n1 wget -P SOURCES
#  - rpmbuild -bs --define '_topdir ./' SPECS/*spec
  - docker run -e MOCK_CONFIG="${MOCK_CONFIG}" -v "$(pwd):/rpmbuild" --privileged=true mmckinst/rpmbuilder
  - find results -type f -ls
